
const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
const KEY='astrodesk_v04';
const VEDIC_OPTIONS=[['birthDetails','Birth Details / Nakshatra'],['planetPositions','Planet Positions'],['dasha','Vimshottari Dasha'],['yoga','Raja Yoga'],['mangalDosha','Mangal Dosha'],['kaalSarp','Kaal Sarp Dosha'],['sadeSati','Sade Sati'],['sarvashtakavarga','Sarvashtakavarga'],['panchang','Panchang'],['upagraha','Upagraha Positions']];
const KP_OPTIONS=[['kpPositions','KP Planet + Cusp Positions'],['planetSignificators','Planet Significators'],['houseSignificators','House Significators'],['dasha','Vimshottari Dasha'],['kpChart','KP Chart']];
const CHARTS=[['rasi','D1 / Rashi'],['drekkana','D3 / Drekkana'],['chaturthamsa','D4 / Chaturthamsa'],['saptamsa','D7 / Saptamsa'],['navamsa','D9 / Navamsa'],['dasamsa','D10 / Dasamsa'],['dwadasamsa','D12 / Dwadasamsa'],['shodasamsa','D16 / Shodasamsa'],['vimsamsa','D20 / Vimsamsa'],['chaturvimsamsa','D24 / Chaturvimsamsa'],['saptavimsamsa','D27 / Saptavimsamsa'],['trimsamsa','D30 / Trimsamsa'],['khavedamsa','D40 / Khavedamsa'],['akshavedamsa','D45 / Akshavedamsa'],['shashtyamsa','D60 / Shashtyamsa'],['bhava','Bhava Chart'],['hora','Hora Chart']];
let db=JSON.parse(localStorage.getItem(KEY)||'null')||{users:[{id:'astro1',name:'Demo Astrologer',email:'astro@example.com',password:'Astro123!',active:true}],branding:{astro1:{brandName:'My Astrology Practice',tagline:'',phone:'',whatsapp:'',email:'astro@example.com',website:'',address:'',signature:'',signatureImage:'',logo:'',disclaimer:'Astrology guidance is interpretive and should be used with personal judgment.'}},reports:[]};
let session=sessionStorage.getItem('astrodesk_session')||'',config={prokeralaClientId:''},active=null,currentTab='editor';
function saveDB(){localStorage.setItem(KEY,JSON.stringify(db))}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
async function loadConfig(){try{config=await (await fetch('/api/config')).json()}catch(e){console.error(e)}}
function user(){return db.users.find(x=>x.id===session)}
function blank(){const now=new Date(),d=now.toISOString().slice(0,10),t=now.toTimeString().slice(0,5);return{id:'r'+Date.now(),userId:session,client:'',dob:'',tob:'',pob:'',coordinates:'',timezone:'',content:'',created:d,updated:d,systems:{vedic:true,kp:false,horary:false},vedic:{ayanamsa:1,options:['birthDetails','planetPositions','dasha'],charts:['rasi','navamsa']},kp:{ayanamsa:5,options:['kpPositions','planetSignificators','houseSignificators','dasha','kpChart']},horary:{ayanamsa:5,question:'',number:'',takingDate:d,takingTime:t,judgmentDate:d,judgmentTime:t},chartStyle:'north-indian',language:'en',calculations:{},pdfLayout:[],page1Blocks:['vedic.chart.rasi','vedic.planetPositions','vedic.chart.navamsa','vedic.dashaPeriods']}}
function render(){if(!session||!user())return login();shell()}
function login(){app.innerHTML=`<div class="login"><div class="login-card"><div class="brand">AstroDesk Report Studio</div><div class="sub">Calculation by software. Interpretation by astrologer.</div><div class="note" style="margin:14px 0">V0.5 · Vedic + KP + Horary + Custom PDF Builder</div><div class="field"><label>Email</label><input id="email" value="astro@example.com"></div><div class="field"><label>Password</label><input id="pass" type="password" value="Astro123!"></div><button class="btn primary full" id="login">Login</button></div></div>`;$('#login').onclick=()=>{const u=db.users.find(x=>x.email.toLowerCase()===$('#email').value.trim().toLowerCase()&&x.password===$('#pass').value);if(!u)return alert('Invalid login');session=u.id;sessionStorage.setItem('astrodesk_session',session);render()}}
function shell(){app.innerHTML=`<div class="shell"><aside class="side"><div class="side-logo">AstroDesk <span class="side-version">V0.5</span></div><div class="nav"><button data-v="dashboard">Dashboard</button><button data-v="new">New Report</button><button data-v="reports">My Reports</button><button data-v="branding">My Branding</button></div></aside><main class="main"><div class="top"><div><div class="title" id="title"></div><div class="sub" id="sub"></div></div><button class="btn" id="logout">Logout</button></div><div id="view"></div></main></div>`;$('#logout').onclick=()=>{session='';sessionStorage.removeItem('astrodesk_session');render()};$('.nav').onclick=e=>{if(e.target.dataset.v)show(e.target.dataset.v)};show('dashboard')}
function setTitle(a,b=''){title.textContent=a;sub.textContent=b}
function show(v){$$('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.v===v));if(v==='dashboard')dashboard();if(v==='new')openReport(blank());if(v==='reports')reports();if(v==='branding')branding()}
function dashboard(){setTitle('Dashboard','Calculate what you need. Write your own interpretation. Choose what goes into the PDF.');const mine=db.reports.filter(r=>r.userId===session);view.innerHTML=`<div class="grid cols4"><div class="card"><div class="label">My Reports</div><div class="stat">${mine.length}</div></div><div class="card"><div class="label">Systems</div><div class="stat" style="font-size:18px">Vedic · KP · Horary</div></div><div class="card"><div class="label">PDF</div><div class="stat" style="font-size:18px">Custom Sections</div></div><div class="card"><div class="label">Prediction</div><div class="stat" style="font-size:18px">Astrologer Only</div></div></div><div class="card" style="margin-top:14px"><b>Start a report</b><div class="sub" style="margin:6px 0 12px">Select systems and calculations. API calls only run for selected sections.</div><button class="btn primary" id="start">+ New Report</button></div>`;$('#start').onclick=()=>openReport(blank())}
function openReport(r){active=r;currentTab='editor';setTitle(r.client?`Report · ${r.client}`:'New Report','Vedic + KP + Horary with a custom branded PDF.');view.innerHTML=`<div class="report-grid"><div class="card sticky" id="left"></div><div><div class="row" style="justify-content:space-between;margin-bottom:9px"><div class="tabs"><button class="tab active" data-tab="editor">Report Editor</button><button class="tab" data-tab="calc">Calculations</button><button class="tab" data-tab="pdf">PDF Builder</button></div><div class="row"><button class="btn" id="save">Save</button><button class="btn primary" id="print">PDF / Print</button></div></div><div id="workspace"></div></div></div>`;renderLeft();tab('editor');$$('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));$('#save').onclick=()=>saveActive();$('#print').onclick=printReport}
function tab(t){currentTab=t;$$('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));if(t==='editor')editorView();if(t==='calc')calcView();if(t==='pdf')pdfView()}
function renderLeft(){const r=active;left.innerHTML=`<b>Client / Reference Details</b><div class="field"><label>Client Name</label><input id="client" value="${esc(r.client)}"></div><div class="field"><label>Date of Birth</label><input id="dob" type="date" value="${esc(r.dob)}"></div><div class="field"><label>Time of Birth</label><input id="tob" type="time" value="${esc(r.tob)}"></div><div class="field"><label>Place (Birth / Horary Location)</label><input id="pob" value="${esc(r.pob)}" placeholder="Type and choose a suggestion"></div><div class="mini" id="loc">${r.coordinates?`Selected: ${esc(r.coordinates)} · ${esc(r.timezone)}`:''}</div><div class="field"><label>Chart Style</label><select id="style"><option value="north-indian">North Indian</option><option value="south-indian">South Indian</option><option value="east-indian">East Indian</option></select></div><div class="field"><label>API Language</label><select id="lang"><option value="en">English</option><option value="hi">Hindi</option><option value="ta">Tamil</option><option value="ml">Malayalam</option></select></div><div class="system-panel"><b>Astrology Systems</b><div class="systems"><button class="system-toggle ${r.systems.vedic?'active':''}" data-s="vedic">Vedic</button><button class="system-toggle ${r.systems.kp?'active':''}" data-s="kp">KP</button><button class="system-toggle ${r.systems.horary?'active':''}" data-s="horary">Horary</button></div><div id="options"></div></div><button class="btn primary full" id="go">Generate Selected Calculations</button><div class="calc-status"><span class="dot" id="dot"></span><span class="mini" id="status">Only selected calculations use the API.</span></div>`;$('#style').value=r.chartStyle;$('#lang').value=r.language;$('#client').oninput=e=>r.client=e.target.value;$('#dob').onchange=e=>r.dob=e.target.value;$('#tob').onchange=e=>r.tob=e.target.value;$('#style').onchange=e=>r.chartStyle=e.target.value;$('#lang').onchange=e=>r.language=e.target.value;$$('[data-s]').forEach(b=>b.onclick=()=>{r.systems[b.dataset.s]=!r.systems[b.dataset.s];renderLeft()});$('#go').onclick=calculate;initLocation();renderOptions()}
function check(prefix,id,n,on){return `<label class="check"><input type="checkbox" data-${prefix}="${id}" ${on?'checked':''}><span>${esc(n)}</span></label>`}
function toggle(arr,id,on){const i=arr.indexOf(id);if(on&&i<0)arr.push(id);if(!on&&i>=0)arr.splice(i,1)}
function renderOptions(){const r=active;let h='';if(r.systems.vedic)h+=`<div class="system-panel"><b>Vedic Astrology</b><div class="field"><label>Ayanamsa</label><select id="va"><option value="1">Lahiri</option><option value="3">Raman</option></select></div><div class="mini" style="margin-bottom:6px">Calculations</div><div class="option-grid">${VEDIC_OPTIONS.map(x=>check('vo',x[0],x[1],r.vedic.options.includes(x[0]))).join('')}</div><div class="mini" style="margin:10px 0 6px">Charts</div><div class="option-grid">${CHARTS.map(x=>check('vc',x[0],x[1],r.vedic.charts.includes(x[0]))).join('')}</div></div>`;if(r.systems.kp)h+=`<div class="system-panel"><b>KP Astrology</b><div class="field"><label>KP Ayanamsa</label><select id="ka"><option value="5">KP</option><option value="45">KP New</option></select></div><div class="option-grid">${KP_OPTIONS.map(x=>check('ko',x[0],x[1],r.kp.options.includes(x[0]))).join('')}</div></div>`;if(r.systems.horary)h+=`<div class="system-panel"><b>Horary / KP Prashna</b><div class="field"><label>Ayanamsa</label><select id="ha"><option value="5">KP</option><option value="45">KP New</option></select></div><div class="field"><label>Question</label><textarea id="hq" rows="2">${esc(r.horary.question)}</textarea></div><div class="field"><label>Horary Number (1–249)</label><input id="hn" type="number" min="1" max="249" value="${esc(r.horary.number)}"></div><div class="field"><label>Time of Taking Number</label><div class="row"><input id="td" type="date" value="${r.horary.takingDate}"><input id="tt" type="time" value="${r.horary.takingTime}"></div></div><div class="field"><label>Time of Judgment</label><div class="row"><input id="jd" type="date" value="${r.horary.judgmentDate}"><input id="jt" type="time" value="${r.horary.judgmentTime}"></div></div><div class="note">Two separate 5-planet Ruling Planet sets are stored: Taking Number time and Judgment time.</div></div>`;options.innerHTML=h;if(r.systems.vedic){va.value=r.vedic.ayanamsa;va.onchange=e=>r.vedic.ayanamsa=+e.target.value;$$('[data-vo]').forEach(x=>x.onchange=()=>toggle(r.vedic.options,x.dataset.vo,x.checked));$$('[data-vc]').forEach(x=>x.onchange=()=>toggle(r.vedic.charts,x.dataset.vc,x.checked))}if(r.systems.kp){ka.value=r.kp.ayanamsa;ka.onchange=e=>r.kp.ayanamsa=+e.target.value;$$('[data-ko]').forEach(x=>x.onchange=()=>toggle(r.kp.options,x.dataset.ko,x.checked))}if(r.systems.horary){ha.value=r.horary.ayanamsa;ha.onchange=e=>r.horary.ayanamsa=+e.target.value;hq.oninput=e=>r.horary.question=e.target.value;hn.oninput=e=>r.horary.number=e.target.value;td.onchange=e=>r.horary.takingDate=e.target.value;tt.onchange=e=>r.horary.takingTime=e.target.value;jd.onchange=e=>r.horary.judgmentDate=e.target.value;jt.onchange=e=>r.horary.judgmentTime=e.target.value}}
function initLocation(){const i=$('#pob');if(!i||!config.prokeralaClientId||typeof LocationSearch==='undefined')return;let picked=false;new LocationSearch(i,d=>{picked=true;active.pob=i.value;active.coordinates=`${d.latitude},${d.longitude}`;active.timezone=d.timezone;i.setCustomValidity('');loc.textContent=`Selected: ${d.latitude}, ${d.longitude} · ${d.timezone}`},{clientId:config.prokeralaClientId,persistKey:'astrodeskV04'});i.addEventListener('change',()=>{active.pob=i.value;if(!picked){active.coordinates='';active.timezone='';loc.textContent='Please select a place from suggestions.'}picked=false})}
function sync(){if($('#client'))active.client=$('#client').value.trim();if($('#dob'))active.dob=$('#dob').value;if($('#tob'))active.tob=$('#tob').value;if($('#pob'))active.pob=$('#pob').value.trim();if($('#editor'))active.content=$('#editor').innerHTML}
function payload(s){const r=active,c={system:s,date:r.dob,time:r.tob,coordinates:r.coordinates,timezone:r.timezone,chartStyle:r.chartStyle,language:r.language};if(s==='vedic')return{...c,ayanamsa:r.vedic.ayanamsa,options:r.vedic.options,charts:r.vedic.charts};if(s==='kp')return{...c,ayanamsa:r.kp.ayanamsa,options:r.kp.options};return{...c,ayanamsa:r.horary.ayanamsa,horary:r.horary}}
async function calculate(){sync();const r=active;if(!r.coordinates||!r.timezone)return alert('Please choose the place from the suggestion list.');const ss=['vedic','kp','horary'].filter(s=>r.systems[s]);if(!ss.length)return alert('Select at least one astrology system.');if((r.systems.vedic||r.systems.kp)&&(!r.dob||!r.tob))return alert('DOB and Time of Birth are required for Vedic/KP.');dot.className='dot busy';status.textContent='Calculating selected sections...';try{for(const s of ss){const resp=await fetch('/api/calculate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload(s))});const out=await resp.json();if(!resp.ok)throw new Error(`${s.toUpperCase()}: ${out.error||'Calculation failed'}`);r.calculations[s]=out.data}ensureLayout();saveActive(true);dot.className='dot ok';status.textContent='Done. Results saved with this report.';tab('calc')}catch(e){dot.className='dot';status.textContent=e.message;alert(e.message)}}
function editorView(){workspace.innerHTML=`<div class="toolbar"><button data-cmd="bold"><b>B</b></button><button data-cmd="italic"><i>I</i></button><button data-cmd="underline"><u>U</u></button><select id="fs"><option value="3">Normal</option><option value="4">Large</option><option value="5">Larger</option></select><button data-cmd="justifyLeft">Left</button><button data-cmd="justifyCenter">Center</button><button data-cmd="justifyRight">Right</button><button data-cmd="insertUnorderedList">• List</button><button data-cmd="insertOrderedList">1. List</button><button id="voice">🎙 Voice to Text</button><button id="translate">Translate</button><button id="polish">Polish Language</button><button data-cmd="undo">Undo</button><button data-cmd="redo">Redo</button></div><div class="editor" id="editor" contenteditable="true">${active.content||''}</div>`;$$('[data-cmd]').forEach(b=>b.onclick=()=>{document.execCommand(b.dataset.cmd,false,null);editor.focus()});fs.onchange=e=>document.execCommand('fontSize',false,e.target.value);editor.oninput=()=>active.content=editor.innerHTML;voice.onclick=voiceType;translate.onclick=()=>alert('Translation will be connected as a language-only service. It will not create astrology predictions.');polish.onclick=()=>alert('Polish Language will improve grammar/wording only. It will never alter the astrologer’s prediction.')}
function voiceType(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return alert('Try Chrome or Edge for voice typing.');const rec=new SR();rec.lang=prompt('bn-IN / hi-IN / en-IN','bn-IN')||'bn-IN';rec.onresult=e=>{editor.focus();document.execCommand('insertText',false,e.results[0][0].transcript);active.content=editor.innerHTML};rec.start()}
function unwrap(x){return x&&typeof x==='object'&&Object.prototype.hasOwnProperty.call(x,'data')?x.data:x}
function scalar(v){if(v==null)return '';if(['string','number','boolean'].includes(typeof v))return String(v);return v.name||v.title||v.symbol||v.value||''}
function pretty(k){return String(k).replace(/_/g,' ').replace(/\b\w/g,m=>m.toUpperCase())}
function rows(x,depth=0){x=unwrap(x);if(Array.isArray(x)&&x.length&&x.every(v=>v&&typeof v==='object'))return x;if(!x||typeof x!=='object'||depth>3)return null;for(const v of Object.values(x)){const r=rows(v,depth+1);if(r)return r}return null}
function renderData(data){const a=rows(data);if(a){const keys=[];a.slice(0,10).forEach(r=>Object.keys(r).forEach(k=>{if(!keys.includes(k)&&scalar(r[k]))keys.push(k)}));const cols=keys.slice(0,8);return `<div class="scrollbox"><table class="data-table"><thead><tr>${cols.map(k=>`<th>${esc(pretty(k))}</th>`).join('')}</tr></thead><tbody>${a.map(r=>`<tr>${cols.map(k=>`<td>${esc(scalar(r[k]))}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}const x=unwrap(data);if(!x||typeof x!=='object')return `<div>${esc(scalar(x))}</div>`;const kv=[];Object.entries(x).forEach(([k,v])=>{const s=scalar(v);if(s)kv.push([pretty(k),s])});return `<div class="kv">${kv.slice(0,20).map(x=>`<div class="k">${esc(x[0])}</div><div>${esc(x[1])}</div>`).join('')||'<div class="k">Status</div><div>Calculated successfully.</div>'}</div>`}
function card(title,data,cls){return `<div class="result-card ${cls}"><h3>${esc(title)}</h3>${renderData(data)}</div>`}
function errorCards(d,cls){return d?.errors&&Object.keys(d.errors).length?`<div class="result-card ${cls}"><h3>Unavailable / API Errors</h3>${Object.entries(d.errors).map(([k,v])=>`<div class="note" style="margin:6px 0"><b>${esc(pretty(k))}</b><br>${esc(v)}</div>`).join('')}</div>`:''}
function cname(k){return (CHARTS.find(x=>x[0]===k)||[k,k])[1]}
function calcView(){const c=active.calculations||{};let h='';if(c.vedic){h+=`<div class="result-card vedic"><h3>Vedic Astrology</h3></div>`;[['birthDetails','Birth Details / Nakshatra'],['planetPositions','Planet Positions'],['dashaPeriods','Vimshottari Dasha'],['yoga','Raja Yoga'],['mangalDosha','Mangal Dosha'],['kaalSarp','Kaal Sarp Dosha'],['sadeSati','Sade Sati'],['sarvashtakavarga','Sarvashtakavarga'],['panchang','Panchang'],['upagraha','Upagraha Positions']].forEach(([k,t])=>{if(c.vedic[k])h+=card(t,c.vedic[k],'vedic')});if(Object.keys(c.vedic.charts||{}).length)h+=`<div class="result-card vedic"><h3>Vedic Charts</h3><div class="charts">${Object.entries(c.vedic.charts).map(([k,v])=>`<div><h4>${esc(cname(k))}</h4><div class="chart">${v}</div></div>`).join('')}</div></div>`;h+=errorCards(c.vedic,'vedic')}if(c.kp){h+=`<div class="result-card kp"><h3>KP Astrology</h3></div>`;if(c.kp.kpPositions)h+=card('KP Planet + Cusp Positions',c.kp.kpPositions,'kp');if(c.kp.planetSignificators)h+=card('Planet Significators',c.kp.planetSignificators,'kp');if(c.kp.houseSignificators)h+=card('House Significators',c.kp.houseSignificators,'kp');if(c.kp.dashaPeriods)h+=card('KP Vimshottari Dasha',c.kp.dashaPeriods,'kp');if(c.kp.kpChartSvg)h+=`<div class="result-card kp"><h3>KP Chart</h3><div class="chart">${c.kp.kpChartSvg}</div></div>`;h+=errorCards(c.kp,'kp')}if(c.horary){const q=c.horary;h+=`<div class="result-card horary"><h3>Horary / KP Prashna</h3><div class="kv"><div class="k">Question</div><div>${esc(q.meta?.question)}</div><div class="k">Horary Number</div><div>${esc(q.meta?.number)}</div><div class="k">Taking Number Time</div><div>${esc(q.meta?.takingDateTime)}</div><div class="k">Judgment Time</div><div>${esc(q.meta?.judgmentDateTime)}</div></div></div>${rpCard('Ruling Planets at the Time of Taking Number',q.taking?.rulingPlanets)}${rpCard('Ruling Planets at the Time of Judgment',q.judgment?.rulingPlanets)}`;if(q.kpChartSvg)h+=`<div class="result-card horary"><h3>Judgment KP Chart</h3><div class="chart">${q.kpChartSvg}</div></div>`;if(q.judgment?.kp)h+=card('Judgment KP Positions',q.judgment.kp,'horary');if(q.planetSignificators)h+=card('Horary Planet Significators',q.planetSignificators,'horary');if(q.houseSignificators)h+=card('Horary House Significators',q.houseSignificators,'horary');if(q.dashaPeriods)h+=card('Horary Dasha',q.dashaPeriods,'horary');h+=`<div class="note">${esc(q.meta?.note||'')}</div>`+errorCards(q,'horary')}workspace.innerHTML=h||`<div class="card"><b>No calculations yet.</b><div class="sub">Choose a system on the left and generate selected calculations.</div></div>`}
function rpCard(t,r={}){return `<div class="result-card horary"><h3>${esc(t)}</h3>${rpInline(r)}</div>`}
function rpInline(r={}){return `<div class="rp-grid">${[['Lagna Lord','lagnaLord'],['Lagna Star Lord','lagnaStarLord'],['Moon Sign Lord','moonSignLord'],['Moon Star Lord','moonStarLord'],['Day Lord','dayLord']].map(([n,k])=>`<div class="rp"><span class="mini">${n}</span><b>${esc(r?.[k]||'—')}</b></div>`).join('')}</div>`}
function available(){const c=active.calculations||{},a=[{id:'client',title:'Client / Reference Details',enabled:true}];if(c.vedic){[['birthDetails','Vedic · Birth Details'],['planetPositions','Vedic · Planet Positions'],['dashaPeriods','Vedic · Vimshottari Dasha'],['yoga','Vedic · Raja Yoga'],['mangalDosha','Vedic · Mangal Dosha'],['kaalSarp','Vedic · Kaal Sarp Dosha'],['sadeSati','Vedic · Sade Sati'],['sarvashtakavarga','Vedic · Sarvashtakavarga'],['panchang','Vedic · Panchang'],['upagraha','Vedic · Upagraha']].forEach(([k,t])=>{if(c.vedic[k])a.push({id:'vedic.'+k,title:t,enabled:true})});Object.keys(c.vedic.charts||{}).forEach(k=>a.push({id:'vedic.chart.'+k,title:'Vedic · '+cname(k),enabled:true}))}if(c.kp){[['kpPositions','KP · Planet + Cusp Positions'],['planetSignificators','KP · Planet Significators'],['houseSignificators','KP · House Significators'],['dashaPeriods','KP · Vimshottari Dasha']].forEach(([k,t])=>{if(c.kp[k])a.push({id:'kp.'+k,title:t,enabled:true})});if(c.kp.kpChartSvg)a.push({id:'kp.chart',title:'KP · Chart',enabled:true})}if(c.horary){a.push({id:'horary.meta',title:'Horary · Question & Number',enabled:true},{id:'horary.rpTaking',title:'Horary · Ruling Planets at Taking Number',enabled:true},{id:'horary.rpJudgment',title:'Horary · Ruling Planets at Judgment',enabled:true});if(c.horary.kpChartSvg)a.push({id:'horary.chart',title:'Horary · Judgment KP Chart',enabled:true});if(c.horary.judgment?.kp)a.push({id:'horary.positions',title:'Horary · Judgment Positions',enabled:true});if(c.horary.planetSignificators)a.push({id:'horary.planetSig',title:'Horary · Planet Significators',enabled:true});if(c.horary.houseSignificators)a.push({id:'horary.houseSig',title:'Horary · House Significators',enabled:true});if(c.horary.dashaPeriods)a.push({id:'horary.dasha',title:'Horary · Dasha',enabled:true})}a.push({id:'interpretation',title:'Astrologer Interpretation',enabled:true},{id:'branding',title:'Signature / Disclaimer',enabled:true});return a}
function ensureLayout(){const avail=available(),map=new Map(avail.map(x=>[x.id,x])),old=active.pdfLayout||[],out=[];for(const x of old)if(map.has(x.id)){out.push({...map.get(x.id),enabled:x.enabled});map.delete(x.id)}for(const x of map.values())out.push(x);active.pdfLayout=out}
function pdfView(){ensureLayout();workspace.innerHTML=`<div class="builder-layout"><div class="card"><b>PDF Content</b><div class="sub">Tick sections and drag them into the order you want.</div><div class="builder-list">${active.pdfLayout.map(x=>`<div class="builder-item" draggable="true" data-item="${x.id}"><span class="drag">≡</span><label><input type="checkbox" data-pdf="${x.id}" ${x.enabled?'checked':''}> ${esc(x.title)}</label><span><button class="btn tiny" data-up="${x.id}">↑</button> <button class="btn tiny" data-down="${x.id}">↓</button></span></div>`).join('')}</div></div><div><div class="row" style="justify-content:space-between;margin-bottom:8px"><b>PDF Preview</b><button class="btn primary" id="pp">Print / Save PDF</button></div><div class="preview-paper">${pdfHTML(false)}</div></div></div>`;$$('[data-pdf]').forEach(x=>x.onchange=()=>{active.pdfLayout.find(y=>y.id===x.dataset.pdf).enabled=x.checked;pdfView()});$$('[data-up]').forEach(x=>x.onclick=()=>move(x.dataset.up,-1));$$('[data-down]').forEach(x=>x.onclick=()=>move(x.dataset.down,1));drag();pp.onclick=printReport}
function move(id,d){const a=active.pdfLayout,i=a.findIndex(x=>x.id===id),j=i+d;if(j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];pdfView()}
function drag(){let id=null;$$('[data-item]').forEach(el=>{el.ondragstart=()=>{id=el.dataset.item;el.classList.add('dragging')};el.ondragend=()=>el.classList.remove('dragging');el.ondragover=e=>e.preventDefault();el.ondrop=e=>{e.preventDefault();if(!id||id===el.dataset.item)return;const a=active.pdfLayout,from=a.findIndex(x=>x.id===id),to=a.findIndex(x=>x.id===el.dataset.item),[it]=a.splice(from,1);a.splice(to,0,it);pdfView()}})}
function section(id){const c=active.calculations||{};if(id==='client')return `<h2>Client / Reference Details</h2><div class="pdf-client"><div><b>Name:</b> ${esc(active.client||'—')}</div><div><b>DOB:</b> ${esc(active.dob||'—')}</div><div><b>Time:</b> ${esc(active.tob||'—')}</div><div><b>Place:</b> ${esc(active.pob||'—')}</div></div>`;if(id==='interpretation')return `<h2>Astrologer Interpretation</h2>${active.content||'<p>—</p>'}`;if(id==='branding'){const b=db.branding[session]||{};return `<h2>Astrologer</h2><p><b>${esc(b.brandName||'')}</b><br>${esc(b.signature||'')}<br>${esc(b.phone||'')} ${b.email?'· '+esc(b.email):''}<br>${esc(b.website||'')}<br>${esc(b.address||'')}</p>${b.disclaimer?`<p class="mini">${esc(b.disclaimer)}</p>`:''}`}if(id.startsWith('vedic.chart.')){const k=id.split('.').pop();return `<h2>${esc(cname(k))}</h2><div class="chart">${c.vedic?.charts?.[k]||''}</div>`}if(id.startsWith('vedic.')){const k=id.split('.')[1],titles={birthDetails:'Birth Details / Nakshatra',planetPositions:'Planet Positions',dashaPeriods:'Vimshottari Dasha',yoga:'Raja Yoga',mangalDosha:'Mangal Dosha',kaalSarp:'Kaal Sarp Dosha',sadeSati:'Sade Sati',sarvashtakavarga:'Sarvashtakavarga',panchang:'Panchang',upagraha:'Upagraha Positions'};return `<h2>${titles[k]||pretty(k)}</h2>${renderData(c.vedic?.[k])}`}if(id==='kp.chart')return `<h2>KP Chart</h2><div class="chart">${c.kp?.kpChartSvg||''}</div>`;if(id.startsWith('kp.')){const k=id.split('.')[1],titles={kpPositions:'KP Planet + Cusp Positions',planetSignificators:'Planet Significators',houseSignificators:'House Significators',dashaPeriods:'KP Vimshottari Dasha'};return `<h2>${titles[k]||pretty(k)}</h2>${renderData(c.kp?.[k])}`}const h=c.horary||{};if(id==='horary.meta')return `<h2>Horary Question</h2><div class="kv"><div class="k">Question</div><div>${esc(h.meta?.question)}</div><div class="k">Horary Number</div><div>${esc(h.meta?.number)}</div><div class="k">Taking Number Time</div><div>${esc(h.meta?.takingDateTime)}</div><div class="k">Judgment Time</div><div>${esc(h.meta?.judgmentDateTime)}</div></div>`;if(id==='horary.rpTaking')return `<h2>Ruling Planets at the Time of Taking Number</h2>${rpInline(h.taking?.rulingPlanets)}`;if(id==='horary.rpJudgment')return `<h2>Ruling Planets at the Time of Judgment</h2>${rpInline(h.judgment?.rulingPlanets)}`;if(id==='horary.chart')return `<h2>Horary Judgment KP Chart</h2><div class="chart">${h.kpChartSvg||''}</div>`;if(id==='horary.positions')return `<h2>Judgment KP Positions</h2>${renderData(h.judgment?.kp)}`;if(id==='horary.planetSig')return `<h2>Horary Planet Significators</h2>${renderData(h.planetSignificators)}`;if(id==='horary.houseSig')return `<h2>Horary House Significators</h2>${renderData(h.houseSignificators)}`;if(id==='horary.dasha')return `<h2>Horary Dasha</h2>${renderData(h.dashaPeriods)}`;return ''}
function pdfHTML(head=true){ensureLayout();const b=db.branding[session]||{};let h=head?`<div class="pdf-head"><div>${b.logo?`<img class="pdf-logo" src="${b.logo}">`:''}</div><div class="pdf-brand"><h1 style="margin:0">${esc(b.brandName||'Astrology Report')}</h1><div>${esc(b.phone||'')} ${b.email?'· '+esc(b.email):''}</div><div>${esc(b.website||'')}</div></div></div>`:'';return h+active.pdfLayout.filter(x=>x.enabled).map(x=>`<section class="preview-section">${section(x.id)}</section>`).join('')}
function printReport(){sync();saveActive(true);printArea.innerHTML=pdfHTML(true);window.print()}
function saveActive(silent=false){sync();active.updated=new Date().toISOString().slice(0,10);ensureLayout();const i=db.reports.findIndex(x=>x.id===active.id);if(i>=0)db.reports[i]=active;else db.reports.push(active);saveDB();if(!silent)alert('Report saved on this browser.')}
function reports(){setTitle('My Reports','Saved locally in this browser in V0.5.');const mine=db.reports.filter(r=>r.userId===session).sort((a,b)=>b.updated.localeCompare(a.updated));view.innerHTML=`<div class="row" style="justify-content:flex-end;margin-bottom:12px"><button class="btn primary" id="nr">+ New Report</button></div><div class="card"><table class="table"><thead><tr><th>Client</th><th>DOB</th><th>Systems</th><th>Updated</th><th></th></tr></thead><tbody>${mine.map(r=>`<tr><td>${esc(r.client||'Untitled')}</td><td>${esc(r.dob)}</td><td>${Object.entries(r.systems||{}).filter(x=>x[1]).map(x=>x[0].toUpperCase()).join(', ')}</td><td>${esc(r.updated)}</td><td><button class="btn" data-open="${r.id}">Open</button></td></tr>`).join('')||'<tr><td colspan="5">No reports yet.</td></tr>'}</tbody></table></div>`;nr.onclick=()=>openReport(blank());$$('[data-open]').forEach(b=>b.onclick=()=>openReport(db.reports.find(r=>r.id===b.dataset.open)))}
function branding(){setTitle('My Branding','Used on final PDFs.');const b=db.branding[session]||{};view.innerHTML=`<div class="grid" style="grid-template-columns:1fr 1fr"><div class="card"><div class="field"><label>Brand / Practice Name</label><input id="bn" value="${esc(b.brandName||'')}"></div><div class="field"><label>Phone / WhatsApp</label><input id="ph" value="${esc(b.phone||'')}"></div><div class="field"><label>Email</label><input id="be" value="${esc(b.email||'')}"></div><div class="field"><label>Website</label><input id="web" value="${esc(b.website||'')}"></div><div class="field"><label>Address</label><input id="addr" value="${esc(b.address||'')}"></div><div class="field"><label>Signature Name</label><input id="sig" value="${esc(b.signature||'')}"></div><div class="field"><label>Disclaimer</label><textarea id="disc" rows="3">${esc(b.disclaimer||'')}</textarea></div><div class="field"><label>Logo</label><input id="logo" type="file" accept="image/*"></div><button class="btn primary" id="sb">Save Branding</button></div><div class="card"><div class="logo-preview" id="lp">${b.logo?`<img src="${b.logo}">`:'Logo'}</div><h2 id="bp">${esc(b.brandName||'My Astrology Practice')}</h2><div class="sub">Professional Astrology Report</div></div></div>`;let ld=b.logo||'';logo.onchange=e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{ld=rd.result;lp.innerHTML=`<img src="${ld}">`};rd.readAsDataURL(f)};bn.oninput=e=>bp.textContent=e.target.value||'My Astrology Practice';sb.onclick=()=>{db.branding[session]={brandName:bn.value,phone:ph.value,email:be.value,website:web.value,address:addr.value,signature:sig.value,disclaimer:disc.value,logo:ld};saveDB();alert('Branding saved.')}}
(async()=>{await loadConfig();render()})();


// ===== AstroDesk V0.5: Fixed Two-Page Astrology PDF =====
function v05NormalizeReport(r){
  if(!r.page1Blocks||!Array.isArray(r.page1Blocks)) r.page1Blocks=['vedic.chart.rasi','vedic.planetPositions','vedic.chart.navamsa','vedic.dashaPeriods'];
  while(r.page1Blocks.length<4)r.page1Blocks.push('');
  r.page1Blocks=r.page1Blocks.slice(0,4);
  return r;
}
function v05Brand(){
  const b=db.branding[session]||{};
  return {
    brandName:b.brandName||'My Astrology Practice',tagline:b.tagline||'',phone:b.phone||'',whatsapp:b.whatsapp||'',
    email:b.email||'',website:b.website||'',address:b.address||'',signature:b.signature||'',signatureImage:b.signatureImage||'',
    logo:b.logo||'',disclaimer:b.disclaimer||''
  };
}
function v05BlockChoices(){
  const list=available().filter(x=>!['client','interpretation','branding'].includes(x.id));
  return list.map(x=>({id:x.id,title:x.title}));
}
function v05ChoiceTitle(id){return (v05BlockChoices().find(x=>x.id===id)||{title:'Not selected'}).title}
function v05EnsureBlocks(){
  v05NormalizeReport(active);
  const choices=v05BlockChoices(),ids=new Set(choices.map(x=>x.id));
  const preferred=['vedic.chart.rasi','vedic.planetPositions','vedic.chart.navamsa','vedic.dashaPeriods','kp.chart','kp.kpPositions','horary.chart','horary.planetSig'];
  for(let i=0;i<4;i++){
    if(active.page1Blocks[i] && ids.has(active.page1Blocks[i]))continue;
    active.page1Blocks[i]=preferred.find(id=>ids.has(id)&&!active.page1Blocks.includes(id))||choices.find(x=>!active.page1Blocks.includes(x.id))?.id||'';
  }
}
function v05DeepFindKey(obj,keys,depth=0){
  if(obj==null||depth>7)return '';
  if(Array.isArray(obj)){for(const v of obj){const x=v05DeepFindKey(v,keys,depth+1);if(x!==''&&x!=null)return x}return ''}
  if(typeof obj!=='object')return '';
  for(const k of keys){if(Object.prototype.hasOwnProperty.call(obj,k)){const v=obj[k];if(v!=null){const s=scalar(v);if(s!=='')return s;if(typeof v==='number')return String(v)}}}
  for(const v of Object.values(obj)){const x=v05DeepFindKey(v,keys,depth+1);if(x!==''&&x!=null)return x}
  return '';
}
function v05PlanetList(data){
  const d=unwrap(data)||{};
  const direct=d.planet_positions||d.planet_position||d.planets;
  if(Array.isArray(direct))return direct;
  const r=rows(d);return Array.isArray(r)?r:[];
}
function v05Planet(data,n){return v05PlanetList(data).find(x=>String(scalar(x.planet)||x.name||'').toLowerCase()===n.toLowerCase())||{}}
function v05HouseList(data){const d=unwrap(data)||{};return Array.isArray(d.houses)?d.houses:[]}
function v05QuickSummary(){
  const c=active.calculations||{},vp=c.vedic?.planetPositions,kp=c.kp?.kpPositions||c.horary?.judgment?.kp;
  const asc=v05Planet(vp,'Ascendant'),moonV=v05Planet(vp,'Moon'),moonK=v05Planet(kp,'Moon');
  const h1=v05HouseList(kp)[0]||{};
  const lagna=scalar(asc.rasi)||scalar(h1.rasi)||v05DeepFindKey(c.vedic?.birthDetails,['lagna','ascendant','ascendant_sign']);
  const rashi=scalar(moonV.rasi)||scalar(moonK.rasi)||v05DeepFindKey(c.vedic?.birthDetails,['rasi','moon_sign','chandra_rasi']);
  const nak=scalar(moonV.nakshatra)||scalar(moonK.nakshatra)||v05DeepFindKey(c.vedic?.birthDetails,['nakshatra','birth_star']);
  let pada=v05DeepFindKey(moonV,['pada','pada_number','charana'])||v05DeepFindKey(c.vedic?.birthDetails,['pada','pada_number','charana']);
  const gana=v05DeepFindKey(c.vedic?.birthDetails,['gana']);
  const sl=scalar(h1.sub_lord)||v05DeepFindKey(h1,['sub_lord']);
  return [
    ['Lagna',lagna||'—'],['Rashi',rashi||'—'],['Nakshatra',nak||'—'],['Pada',pada||'—'],['Gana',gana||'—'],['Lagna Sub Lord (1SL)',sl||'—']
  ];
}
function v05StripHeading(html){return String(html||'').replace(/^\s*<h2[^>]*>.*?<\/h2>/i,'')}
function v05BlockHTML(id,index){
  if(!id)return `<div class="report-block empty"><div class="block-title">Block ${index+1}</div><div class="block-empty">Not selected</div></div>`;
  const body=v05StripHeading(section(id));
  return `<div class="report-block"><div class="block-title">${esc(v05ChoiceTitle(id))}</div><div class="block-body">${body}</div></div>`;
}
function v05HeaderHTML(){
  const b=v05Brand();
  return `<div class="fixed-header"><div class="fixed-logo">${b.logo?`<img src="${b.logo}">`:'<div class="logo-placeholder">Logo</div>'}</div><div class="fixed-brand"><div class="brand-name">${esc(b.brandName)}</div>${b.tagline?`<div class="brand-tagline">${esc(b.tagline)}</div>`:''}</div><div class="fixed-contact"><div><b>Website</b> ${esc(b.website||'—')}</div><div><b>Mob</b> ${esc(b.phone||'—')}</div><div><b>WhatsApp</b> ${esc(b.whatsapp||'—')}</div><div><b>Email</b> ${esc(b.email||'—')}</div></div></div>`;
}
function v05ClientRow(){return `<div class="client-strip"><div><span>Name</span><b>${esc(active.client||'—')}</b></div><div><span>DOB</span><b>${esc(active.dob||'—')}</b></div><div><span>Time</span><b>${esc(active.tob||'—')}</b></div><div><span>Place</span><b>${esc(active.pob||'—')}</b></div></div>`}
function v05QuickRow(){return `<div class="quick-strip">${v05QuickSummary().map(([k,v])=>`<div><span>${esc(k)}</span><b>${esc(v)}</b></div>`).join('')}</div>`}
function v05Signature(){const b=v05Brand();return `<div class="fixed-footer"><div class="footer-disclaimer">${esc(b.disclaimer||'')}</div><div class="signature-box">${b.signatureImage?`<img src="${b.signatureImage}">`:''}<div>${esc(b.signature||'Astrologer Signature')}</div></div></div>`}
function v05Page1(){v05EnsureBlocks();return `<section class="pdf-page page-one">${v05HeaderHTML()}${v05ClientRow()}${v05QuickRow()}<div class="report-block-grid">${active.page1Blocks.map((x,i)=>v05BlockHTML(x,i)).join('')}</div>${v05Signature()}</section>`}
function v05PredictionClass(){const n=(active.content||'').replace(/<[^>]+>/g,'').length;return n>7500?'prediction tiny':n>5000?'prediction small':'prediction'}
function v05Page2(){const b=v05Brand();return `<section class="pdf-page page-two"><div class="prediction-head"><div><b>${esc(b.brandName)}</b>${b.tagline?`<span>${esc(b.tagline)}</span>`:''}</div><div>${esc(active.client||'Personal Prediction')}</div></div><h1>Personal Prediction</h1><div class="${v05PredictionClass()}">${active.content||'<p>Write the astrologer’s personal prediction in the Report Editor.</p>'}</div><div class="prediction-foot">${esc(b.website||'')} ${b.phone?' · '+esc(b.phone):''}</div></section>`}
function pdfHTML(){v05EnsureBlocks();return `<div class="two-page-report">${v05Page1()}${v05Page2()}</div>`}
function pdfView(){
  v05EnsureBlocks();
  const choices=v05BlockChoices();
  const opts=(selected)=>`<option value="">None</option>${choices.map(x=>`<option value="${esc(x.id)}" ${x.id===selected?'selected':''}>${esc(x.title)}</option>`).join('')}`;
  const textLen=(active.content||'').replace(/<[^>]+>/g,'').length;
  workspace.innerHTML=`<div class="fixed-builder"><div class="card fixed-controls"><h3 style="margin-top:0">Fixed 2-Page PDF</h3><div class="sub">Page 1 is always the structured summary. Choose exactly what appears in its four blocks. Page 2 is your personal prediction.</div><div class="note" style="margin:12px 0"><b>Page 1:</b> Branding + Client Details + Lagna/Rashi/Nakshatra/Pada/Gana/1SL + 4 blocks + Signature.<br><b>Page 2:</b> Personal Prediction only.</div>${active.page1Blocks.map((x,i)=>`<div class="field"><label>Block ${i+1} — ${i<2?'Top':'Bottom'} ${i%2===0?'Left':'Right'}</label><select data-block="${i}">${opts(x)}</select></div>`).join('')}<button class="btn" id="recommended">Use Recommended Layout</button><div class="mini" style="margin-top:10px">Prediction length: ${textLen} characters. ${textLen>7500?'<b>Very long — shorten it so Page 2 stays readable.</b>':textLen>5000?'The PDF will use a smaller font on Page 2.':'Good for a one-page prediction.'}</div><button class="btn primary full" id="pp" style="margin-top:12px">Print / Save 2-Page PDF</button></div><div class="fixed-preview">${pdfHTML()}</div></div>`;
  $$('[data-block]').forEach(s=>s.onchange=()=>{active.page1Blocks[+s.dataset.block]=s.value;saveActive(true);pdfView()});
  $('#recommended').onclick=()=>{active.page1Blocks=['vedic.chart.rasi','vedic.planetPositions','vedic.chart.navamsa','vedic.dashaPeriods'];v05EnsureBlocks();saveActive(true);pdfView()};
  $('#pp').onclick=printReport;
}
function printReport(){sync();saveActive(true);printArea.innerHTML=pdfHTML();window.print()}
function saveActive(silent=false){sync();v05NormalizeReport(active);active.updated=new Date().toISOString().slice(0,10);const i=db.reports.findIndex(x=>x.id===active.id);if(i>=0)db.reports[i]=active;else db.reports.push(active);saveDB();if(!silent)alert('Report saved on this browser.')}
function dashboard(){setTitle('Dashboard','Vedic + KP + Horary calculation with a fixed professional 2-page PDF.');const mine=db.reports.filter(r=>r.userId===session);view.innerHTML=`<div class="grid cols4"><div class="card"><div class="label">My Reports</div><div class="stat">${mine.length}</div></div><div class="card"><div class="label">Systems</div><div class="stat" style="font-size:18px">Vedic · KP · Horary</div></div><div class="card"><div class="label">PDF</div><div class="stat" style="font-size:18px">Fixed 2 Pages</div></div><div class="card"><div class="label">Page 1</div><div class="stat" style="font-size:18px">4 Selectable Blocks</div></div></div><div class="card" style="margin-top:14px"><b>Report flow</b><div class="sub" style="margin:6px 0 12px">Calculate → choose 4 summary blocks → write personal prediction → save exactly 2 PDF pages.</div><button class="btn primary" id="start">+ New Report</button></div>`;$('#start').onclick=()=>openReport(blank())}
function openReport(r){active=v05NormalizeReport(r);currentTab='editor';setTitle(r.client?`Report · ${r.client}`:'New Report','Page 1: structured astrology summary · Page 2: personal prediction.');view.innerHTML=`<div class="report-grid"><div class="card sticky" id="left"></div><div><div class="row" style="justify-content:space-between;margin-bottom:9px"><div class="tabs"><button class="tab active" data-tab="editor">Personal Prediction</button><button class="tab" data-tab="calc">Calculations</button><button class="tab" data-tab="pdf">2-Page PDF</button></div><div class="row"><button class="btn" id="save">Save</button><button class="btn primary" id="print">PDF / Print</button></div></div><div id="workspace"></div></div></div>`;renderLeft();tab('editor');$$('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));$('#save').onclick=()=>saveActive();$('#print').onclick=printReport}
function editorView(){workspace.innerHTML=`<div class="card" style="margin-bottom:10px"><b>Page 2 — Personal Prediction</b><div class="sub">Write freely like Word/Google Docs. This entire editor becomes Page 2 of the final PDF. The software does not write astrology predictions for you.</div></div><div class="toolbar"><button data-cmd="bold"><b>B</b></button><button data-cmd="italic"><i>I</i></button><button data-cmd="underline"><u>U</u></button><select id="fs"><option value="3">Normal</option><option value="4">Large</option><option value="5">Larger</option></select><button data-cmd="justifyLeft">Left</button><button data-cmd="justifyCenter">Center</button><button data-cmd="justifyRight">Right</button><button data-cmd="insertUnorderedList">• List</button><button data-cmd="insertOrderedList">1. List</button><button id="voice">🎙 Voice to Text</button><button id="translate">Translate</button><button id="polish">Polish Language</button><button data-cmd="undo">Undo</button><button data-cmd="redo">Redo</button></div><div class="editor" id="editor" contenteditable="true">${active.content||''}</div>`;$$('[data-cmd]').forEach(b=>b.onclick=()=>{document.execCommand(b.dataset.cmd,false,null);editor.focus()});fs.onchange=e=>document.execCommand('fontSize',false,e.target.value);editor.oninput=()=>active.content=editor.innerHTML;voice.onclick=voiceType;translate.onclick=()=>alert('Translation will be connected as a language-only service. It will not create astrology predictions.');polish.onclick=()=>alert('Polish Language will improve grammar/wording only. It will never alter the astrologer’s prediction.')}
function branding(){
  setTitle('My Branding','Header, contact details and signature used on Page 1.');const b=v05Brand();
  view.innerHTML=`<div class="grid" style="grid-template-columns:1fr 1fr"><div class="card"><div class="field"><label>Brand / Practice Name</label><input id="bn" value="${esc(b.brandName)}"></div><div class="field"><label>Short Tagline</label><input id="tag" value="${esc(b.tagline)}" placeholder="A short line under your brand name"></div><div class="field"><label>Mobile</label><input id="ph" value="${esc(b.phone)}"></div><div class="field"><label>WhatsApp</label><input id="wa" value="${esc(b.whatsapp)}"></div><div class="field"><label>Email</label><input id="be" value="${esc(b.email)}"></div><div class="field"><label>Website</label><input id="web" value="${esc(b.website)}"></div><div class="field"><label>Address</label><input id="addr" value="${esc(b.address)}"></div><div class="field"><label>Signature Name</label><input id="sig" value="${esc(b.signature)}"></div><div class="field"><label>Disclaimer</label><textarea id="disc" rows="3">${esc(b.disclaimer)}</textarea></div><div class="field"><label>Logo</label><input id="logo" type="file" accept="image/*"></div><div class="field"><label>Signature Image (optional)</label><input id="sigimg" type="file" accept="image/*"></div><button class="btn primary" id="sb">Save Branding</button></div><div class="card"><div class="logo-preview" id="lp">${b.logo?`<img src="${b.logo}">`:'Logo'}</div><h2 id="bp">${esc(b.brandName)}</h2><div class="sub" id="tp">${esc(b.tagline||'Short Tagline')}</div><div style="margin-top:24px"><b>Signature Preview</b><div class="signature-preview" id="sp">${b.signatureImage?`<img src="${b.signatureImage}">`:esc(b.signature||'Astrologer Signature')}</div></div></div></div>`;
  let ld=b.logo,sd=b.signatureImage;
  const fileData=(input,cb)=>input.onchange=e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>cb(rd.result);rd.readAsDataURL(f)};
  fileData(logo,x=>{ld=x;lp.innerHTML=`<img src="${x}">`});fileData(sigimg,x=>{sd=x;sp.innerHTML=`<img src="${x}">`});bn.oninput=e=>bp.textContent=e.target.value||'My Astrology Practice';tag.oninput=e=>tp.textContent=e.target.value||'Short Tagline';
  sb.onclick=()=>{db.branding[session]={brandName:bn.value,tagline:tag.value,phone:ph.value,whatsapp:wa.value,email:be.value,website:web.value,address:addr.value,signature:sig.value,signatureImage:sd,disclaimer:disc.value,logo:ld};saveDB();alert('Branding saved.')};
}
