const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const KEY='astrodesk_v03';
let db=JSON.parse(localStorage.getItem(KEY)||'null')||{
 users:[{id:'astro1',name:'Demo Astrologer',email:'astro@example.com',password:'Astro123!',active:true}],
 branding:{astro1:{brandName:'My Astrology Practice',phone:'',email:'astro@example.com',website:'',signature:'',logo:''}},
 reports:[]
};
let session=sessionStorage.getItem('astrodesk_session')||'';
let config={prokeralaClientId:''};
function save(){localStorage.setItem(KEY,JSON.stringify(db))}function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
async function loadConfig(){try{const r=await fetch('/api/config');config=await r.json()}catch(e){console.error(e)}}
function currentUser(){return db.users.find(u=>u.id===session)}
function render(){if(!session||!currentUser())return login();shell()}
function login(){app.innerHTML=`<div class="login"><div class="login-card"><div class="brand">AstroDesk Report Studio</div><div class="sub">Calculation by software. Interpretation by astrologer.</div><div class="field"><label>Email</label><input id="email" value="astro@example.com"></div><div class="field"><label>Password</label><input id="pass" type="password" value="Astro123!"></div><button class="btn primary full" id="login">Login</button><div class="note" style="margin-top:14px">Prototype login only. Production user accounts will move to secure cloud authentication later.</div></div></div>`;$('#login').onclick=()=>{const u=db.users.find(x=>x.email.toLowerCase()===$('#email').value.trim().toLowerCase()&&x.password===$('#pass').value);if(!u)return alert('Invalid login');session=u.id;sessionStorage.setItem('astrodesk_session',session);render()}}
function shell(){const u=currentUser();app.innerHTML=`<div class="shell"><aside class="side"><div class="side-logo">AstroDesk</div><div class="nav"><button data-v="dashboard">Dashboard</button><button data-v="new">New Report</button><button data-v="reports">My Reports</button><button data-v="branding">My Branding</button></div></aside><main class="main"><div class="top"><div><div class="title" id="title">Dashboard</div><div class="sub" id="sub"></div></div><button class="btn" id="logout">Logout</button></div><div id="view"></div></main></div>`;$('#logout').onclick=()=>{session='';sessionStorage.removeItem('astrodesk_session');render()};$('.nav').onclick=e=>{if(e.target.dataset.v)show(e.target.dataset.v)};show('dashboard')}
function show(v){$$('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.v===v));if(v==='dashboard')dashboard();if(v==='new')reportEditor();if(v==='reports')reports();if(v==='branding')branding()}
function setTitle(t,s=''){title.textContent=t;sub.textContent=s}
function dashboard(){setTitle('Dashboard','Keep it simple: create, write and export reports.');const mine=db.reports.filter(r=>r.userId===session);view.innerHTML=`<div class="grid cols4"><div class="card"><div class="label">My Reports</div><div class="stat">${mine.length}</div></div><div class="card"><div class="label">Calculation</div><div class="stat" style="font-size:18px">Prokerala API</div></div><div class="card"><div class="label">Editor</div><div class="stat" style="font-size:18px">Free-form</div></div><div class="card"><div class="label">Prediction</div><div class="stat" style="font-size:18px">Astrologer only</div></div></div><div class="card" style="margin-top:14px"><b>Start a new report</b><div class="sub" style="margin:6px 0 12px">Birth details → real horoscope calculation → your own writing → PDF.</div><button class="btn primary" id="start">+ New Report</button></div>`;$('#start').onclick=()=>show('new')}
function reportEditor(existing=null){setTitle(existing?'Edit Report':'New Report','Word/Google Docs style writing with real horoscope calculation.');const r=existing||{id:'r'+Date.now(),userId:session,client:'',dob:'',tob:'',pob:'',content:'',created:new Date().toISOString().slice(0,10),updated:new Date().toISOString().slice(0,10)};view.innerHTML=`<div class="report-grid"><form class="card sticky" id="birthForm"><b>Birth Details</b><div class="field"><label>Client Name</label><input id="client" value="${esc(r.client)}"></div><div class="field"><label>Date of Birth</label><input id="dob" type="date" value="${esc(r.dob)}"></div><div class="field"><label>Time of Birth</label><input id="tob" type="time" value="${esc(r.tob)}"></div><div class="field"><label>Place of Birth</label><input id="pob" class="prokerala-location-input" placeholder="Start typing, then select a suggestion" value="${esc(r.pob)}"></div><button type="button" class="btn primary full" id="calc">Generate Horoscope</button><div class="mini" id="locStatus" style="margin-top:8px"></div><div class="results" id="results"></div></form><div><div class="row no-print" style="justify-content:space-between;margin-bottom:9px"><div><b>Report Editor</b><div class="mini">No fixed Career/Marriage templates.</div></div><div class="actions"><button class="btn" id="save">Save</button><button class="btn primary" id="pdf">PDF / Print</button></div></div><div class="toolbar no-print"><button data-cmd="bold"><b>B</b></button><button data-cmd="italic"><i>I</i></button><button data-cmd="underline"><u>U</u></button><select id="fontSize"><option value="3">Normal</option><option value="4">Large</option><option value="5">Larger</option></select><button data-cmd="justifyLeft">Left</button><button data-cmd="justifyCenter">Center</button><button data-cmd="justifyRight">Right</button><button data-cmd="insertUnorderedList">• List</button><button data-cmd="insertOrderedList">1. List</button><button id="voice">🎙 Voice to Text</button><button id="translate">Translate</button><button id="polish">Polish Language</button><button data-cmd="undo">Undo</button><button data-cmd="redo">Redo</button></div><div class="editor" id="editor" contenteditable="true">${r.content||''}</div></div></div>`;initLocation();$$('[data-cmd]').forEach(b=>b.onclick=()=>{document.execCommand(b.dataset.cmd,false,null);editor.focus()});fontSize.onchange=e=>{document.execCommand('fontSize',false,e.target.value);editor.focus()};calc.onclick=()=>calculate();save.onclick=()=>saveReport(r);pdf.onclick=()=>{saveReport(r,true);window.print()};voice.onclick=()=>voiceType();translate.onclick=()=>alert('Translation will be connected in the next language-service build.');polish.onclick=()=>alert('Polish Language will improve wording only; it will never change the astrologer’s prediction.')}
function initLocation(){const input=$('#pob'),form=$('#birthForm');if(!input||!form)return;if(!config.prokeralaClientId){locStatus.textContent='Prokerala Client ID is not configured in Vercel yet.';return}if(typeof LocationSearch==='undefined'){locStatus.textContent='Location search failed to load.';return}const c=document.createElement('input'),t=document.createElement('input');c.type=t.type='hidden';c.name='coordinates';t.name='timezone';form.append(c,t);new LocationSearch(input,d=>{c.value=`${d.latitude},${d.longitude}`;t.value=d.timezone;input.setCustomValidity('');locStatus.textContent=`Selected: ${d.latitude}, ${d.longitude} · ${d.timezone}`},{clientId:config.prokeralaClientId,persistKey:'astrodeskLoc'});input.addEventListener('change',()=>{if(!c.value)input.setCustomValidity('Please select a place from the suggestions list')})}
async function calculate(){const form=$('#birthForm');const coordinates=form.elements.coordinates?.value,timezone=form.elements.timezone?.value;if(!dob.value||!tob.value||!pob.value.trim())return alert('Enter date, time and birth place.');if(!coordinates||!timezone)return alert('Please select the birth place from the suggestion list.');results.innerHTML='<div class="note">Calculating real horoscope...</div>';try{const response=await fetch('/api/horoscope',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({date:dob.value,time:tob.value,coordinates,timezone,ayanamsa:1,language:'en',chartStyle:'north-indian'})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Calculation failed');renderResult(data)}catch(e){results.innerHTML=`<div class="note">${esc(e.message)}</div>`}}
function unwrap(x){return x&&typeof x==='object'&&'data'in x?x.data:x}function renderResult(d){const birth=unwrap(d.birthDetails),planets=unwrap(d.planetPosition),dasha=unwrap(d.dashaPeriods);results.innerHTML=`<div class="result-card"><h4>Birth Details / Nakshatra</h4><pre>${esc(JSON.stringify(birth,null,2))}</pre></div><div class="result-card"><h4>Planet Positions</h4><pre>${esc(JSON.stringify(planets,null,2))}</pre></div><div class="result-card"><h4>Vimshottari Dasha</h4><pre>${esc(JSON.stringify(dasha,null,2))}</pre></div><div class="charts"><div class="result-card chart"><h4>D1 / Rashi</h4>${d.rasiChartSvg||''}</div><div class="result-card chart"><h4>D9 / Navamsa</h4>${d.navamsaChartSvg||''}</div></div>`}
function saveReport(r,silent=false){r.client=client.value.trim()||'Untitled Client';r.dob=dob.value;r.tob=tob.value;r.pob=pob.value.trim();r.content=editor.innerHTML;r.updated=new Date().toISOString().slice(0,10);const i=db.reports.findIndex(x=>x.id===r.id);if(i>=0)db.reports[i]=r;else db.reports.push(r);save();if(!silent)alert('Report saved on this browser.')}
function voiceType(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return alert('Voice typing is not supported in this browser. Try Chrome or Edge.');const lang=prompt('Language: bn-IN (Bengali), hi-IN (Hindi), en-IN (English)','bn-IN')||'bn-IN';const rec=new SR();rec.lang=lang;rec.interimResults=false;rec.onresult=e=>{editor.focus();document.execCommand('insertText',false,e.results[0][0].transcript)};rec.start()}
function reports(){setTitle('My Reports','Saved locally in this browser for the prototype.');const mine=db.reports.filter(r=>r.userId===session).sort((a,b)=>b.updated.localeCompare(a.updated));view.innerHTML=`<div class="row" style="justify-content:flex-end;margin-bottom:12px"><button class="btn primary" id="nr">+ New Report</button></div><div class="card"><table class="table"><thead><tr><th>Client</th><th>DOB</th><th>Place</th><th>Updated</th><th></th></tr></thead><tbody>${mine.map(r=>`<tr><td>${esc(r.client)}</td><td>${esc(r.dob)}</td><td>${esc(r.pob)}</td><td>${esc(r.updated)}</td><td><button class="btn" data-open="${r.id}">Open</button></td></tr>`).join('')||'<tr><td colspan="5">No reports yet.</td></tr>'}</tbody></table></div>`;nr.onclick=()=>show('new');$$('[data-open]').forEach(b=>b.onclick=()=>reportEditor(db.reports.find(r=>r.id===b.dataset.open)))}
function branding(){setTitle('My Branding','Used for the astrologer’s identity and future final PDF layout.');const b=db.branding[session]||{};view.innerHTML=`<div class="grid" style="grid-template-columns:1fr 1fr"><div class="card"><div class="field"><label>Brand / Practice Name</label><input id="brandName" value="${esc(b.brandName||'')}"></div><div class="field"><label>Phone / WhatsApp</label><input id="phone" value="${esc(b.phone||'')}"></div><div class="field"><label>Email</label><input id="bemail" value="${esc(b.email||'')}"></div><div class="field"><label>Website</label><input id="website" value="${esc(b.website||'')}"></div><div class="field"><label>Signature Name</label><input id="signature" value="${esc(b.signature||'')}"></div><div class="field"><label>Logo</label><input id="logo" type="file" accept="image/*"></div><button class="btn primary" id="sb">Save Branding</button></div><div class="card"><div class="logo-preview" id="lp">${b.logo?`<img src="${b.logo}">`:'Logo'}</div><h2 id="bp">${esc(b.brandName||'My Astrology Practice')}</h2><div class="sub">Professional Astrology Report</div></div></div>`;let logoData=b.logo||'';logo.onchange=e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{logoData=rd.result;lp.innerHTML=`<img src="${logoData}">`};rd.readAsDataURL(f)};brandName.oninput=e=>bp.textContent=e.target.value||'My Astrology Practice';sb.onclick=()=>{db.branding[session]={brandName:brandName.value,phone:phone.value,email:bemail.value,website:website.value,signature:signature.value,logo:logoData};save();alert('Branding saved.')}}
(async()=>{await loadConfig();render()})();
